Crud validacao nivel
aceleradora-TW/easy-beasy pull request #7
Opened 2019-10-01 18:04 UTC by GabrieRabelo

Cria na classe validações de:
- Entradas de número.
- Entradas de nomes.

2019-10-01 19:08 UTC, riguelbf reviewed
Apenas uma sugestão. E se tivéssemos uma classe que validasse cada dominio (Nivel, Estagio, Subnivel, etc...) e essa classe retornasse a lista de erros? 

algo como isso 
`public static class ValidadorDeNivel () {

    private final ArrayList<String> erros;

    public List<String> validar(Nivel nivel) {
        // faz todas as validaçoes aqui
    }

    public boolean isValida(){
        return erros.isEmpty();
    }

    public String getErros() {
        String mensagensDeErros = "";

        for(String erro : erros) {
            mensagensDeErros += "\n" + erro;
        }

        return mensagensDeErros;
    }
}`

2019-10-02 12:48 UTC, yrachid approved these changes

2019-10-02 17:29 UTC, JefersonCruz3 commented
> Apenas uma sugestão. E se tivéssemos uma classe que validasse cada dominio (Nivel, Estagio, Subnivel, etc...) e essa classe retornasse a lista de erros?
> 
> algo como isso
> `public static class ValidadorDeNivel () {
> 
> ```
> private final ArrayList<String> erros;
> 
> public List<String> validar(Nivel nivel) {
>     // faz todas as validaçoes aqui
> }
> 
> public boolean isValida(){
>     return erros.isEmpty();
> }
> 
> public String getErros() {
>     String mensagensDeErros = "";
> 
>     for(String erro : erros) {
>         mensagensDeErros += "\n" + erro;
>     }
> 
>     return mensagensDeErros;
> }
> ```
> 
> }`

2019-10-03 18:33 UTC, jonaathansouzaa requested changes

2019-10-03 18:33 UTC, jsouzajava commented on src/main/java/com/thoughtworks/aceleradora/dominio/GerenciadorEstagio.java
> +        if (novoSubnivel.getEstagios().isEmpty()) {
Não faria sentido ter uma regra para validar se não é nula a lista? Caso seja nula e tente dar o método `isEmpty()` vai dar um NullPointerException

2019-10-03 18:33 UTC, jsouzajava commented on src/main/java/com/thoughtworks/aceleradora/dominio/Nivel.java
> +        subniveis = new ArrayList<>();
Por padrão é recomendado usar `this.subniveis = new ArrayList<>();`

2019-10-03 18:34 UTC, jonaathansouzaa approved these changes

2019-10-07 14:32 UTC, riguelbf commented on src/main/java/com/thoughtworks/aceleradora/dominio/ValidacoesBase.java
> +//    public static boolean nomeRepetido(List<Nivel> niveis, String nome) {
Por favor remova os codigos mortos (comentarios, etic)

2019-10-07 14:32 UTC, riguelbf commented on src/main/java/com/thoughtworks/aceleradora/dominio/GerenciadorEstagio.java
> +        for (int i = 0; i < novoSubnivel.getEstagios().size(); i++) {
Temos que iniciar a pratica de formação de código antes de abrir o PR pois estamos tendo muitas linhas modificadas em relação a identação, linhas em branco, etc...

2019-10-07 14:32 UTC, riguelbf commented on src/main/java/com/thoughtworks/aceleradora/dominio/ValidacoesBase.java
> +public abstract class ValidacoesBase {
Colocar o nome de classes no infinitivo me parece uma abordagem melhor (sugestão)

2019-10-07 14:32 UTC, riguelbf commented on src/main/java/com/thoughtworks/aceleradora/dominio/ValidacoesBase.java
> +public abstract class ValidacoesBase {
Antes: ValidacoesBase 
Depois: ValidadorBase

2019-10-07 14:32 UTC, riguelbf commented on src/main/java/com/thoughtworks/aceleradora/dominio/ValidadorNivel.java
> +        }
Trocar esse bloco de código para utlizar a função "ehNumero" da classe base ValidacoesBase já que temos uma herança aqui

2019-10-07 14:32 UTC, riguelbf commented on src/main/java/com/thoughtworks/aceleradora/dominio/Pessoa.java
> +    }
Se temos uma sobrecarga de construtor porque teriamos um construtor vazio?

2019-10-08 14:16 UTC, cassia11 commented on src/main/java/com/thoughtworks/aceleradora/dominio/Pessoa.java
> +    }
construtor vazio removido :)

2019-10-08 14:52 UTC, cassia11 commented on src/main/java/com/thoughtworks/aceleradora/dominio/GerenciadorEstagio.java
> +        if (novoSubnivel.getEstagios().isEmpty()) {
Acreditamos que faz mais sentido realizar essa validação em uma possível branch Validacao Estágio, como estamos fazendo as validações de níveis por enquanto deixamos anotada essa sugestão.

2019-10-08 14:55 UTC, merged